//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echo.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResx() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Echo.Resources.LangResx", typeof(LangResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Settings 的本地化字符串。
        /// </summary>
        public static string Advanced_Settings {
            get {
                return ResourceManager.GetString("Advanced_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aspect Ratio 的本地化字符串。
        /// </summary>
        public static string Aspect_Ratio {
            get {
                return ResourceManager.GetString("Aspect_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Detect 的本地化字符串。
        /// </summary>
        public static string Auto_Detect {
            get {
                return ResourceManager.GetString("Auto_Detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Save Vocabulary 的本地化字符串。
        /// </summary>
        public static string Auto_Save_Vocabulary {
            get {
                return ResourceManager.GetString("Auto_Save_Vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backward Shortcut 的本地化字符串。
        /// </summary>
        public static string Backward_Shortcut {
            get {
                return ResourceManager.GetString("Backward_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backward Time 的本地化字符串。
        /// </summary>
        public static string Backward_Time {
            get {
                return ResourceManager.GetString("Backward_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Check_for_Updates {
            get {
                return ResourceManager.GetString("Check_for_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Token 的本地化字符串。
        /// </summary>
        public static string Configure_Token {
            get {
                return ResourceManager.GetString("Configure_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control 的本地化字符串。
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dictionary API 的本地化字符串。
        /// </summary>
        public static string Dictionary_API {
            get {
                return ResourceManager.GetString("Dictionary_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Echo Token 的本地化字符串。
        /// </summary>
        public static string Echo_Token {
            get {
                return ResourceManager.GetString("Echo_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export as Markdown 的本地化字符串。
        /// </summary>
        public static string Export_as_Markdown {
            get {
                return ResourceManager.GetString("Export_as_Markdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export as SQLite File 的本地化字符串。
        /// </summary>
        public static string Export_as_SQLite_File {
            get {
                return ResourceManager.GetString("Export_as_SQLite_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feedback 的本地化字符串。
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixed Time 的本地化字符串。
        /// </summary>
        public static string Fixed_Time {
            get {
                return ResourceManager.GetString("Fixed_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward Shortcut 的本地化字符串。
        /// </summary>
        public static string Forward_Shortcut {
            get {
                return ResourceManager.GetString("Forward_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward Time 的本地化字符串。
        /// </summary>
        public static string Forward_Time {
            get {
                return ResourceManager.GetString("Forward_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fullscreen 的本地化字符串。
        /// </summary>
        public static string Fullscreen {
            get {
                return ResourceManager.GetString("Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fullscreen Lock 的本地化字符串。
        /// </summary>
        public static string Fullscreen_Lock {
            get {
                return ResourceManager.GetString("Fullscreen_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input 的本地化字符串。
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Large 的本地化字符串。
        /// </summary>
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Learn 的本地化字符串。
        /// </summary>
        public static string Learn {
            get {
                return ResourceManager.GetString("Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Learning Language 的本地化字符串。
        /// </summary>
        public static string Learning_Language {
            get {
                return ResourceManager.GetString("Learning_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium 的本地化字符串。
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Sentence 的本地化字符串。
        /// </summary>
        public static string Next_Sentence {
            get {
                return ResourceManager.GetString("Next_Sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File 的本地化字符串。
        /// </summary>
        public static string Open_File {
            get {
                return ResourceManager.GetString("Open_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Subtitles 的本地化字符串。
        /// </summary>
        public static string Open_Subtitles {
            get {
                return ResourceManager.GetString("Open_Subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oxford Dictionary 的本地化字符串。
        /// </summary>
        public static string Oxford_Dictionary {
            get {
                return ResourceManager.GetString("Oxford_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Sentence 的本地化字符串。
        /// </summary>
        public static string Previous_Sentence {
            get {
                return ResourceManager.GetString("Previous_Sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purchase 的本地化字符串。
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent Files 的本地化字符串。
        /// </summary>
        public static string Recent_Files {
            get {
                return ResourceManager.GetString("Recent_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Vocabulary by Video 的本地化字符串。
        /// </summary>
        public static string Save_Vocabulary_by_Video {
            get {
                return ResourceManager.GetString("Save_Vocabulary_by_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Subtitles 的本地化字符串。
        /// </summary>
        public static string Select_Subtitles {
            get {
                return ResourceManager.GetString("Select_Subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sentence Analysis 的本地化字符串。
        /// </summary>
        public static string Sentence_Analysis {
            get {
                return ResourceManager.GetString("Sentence_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sentence Analysis API 的本地化字符串。
        /// </summary>
        public static string Sentence_Analysis_API {
            get {
                return ResourceManager.GetString("Sentence_Analysis_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcuts 的本地化字符串。
        /// </summary>
        public static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Subtitles 的本地化字符串。
        /// </summary>
        public static string Show_Subtitles {
            get {
                return ResourceManager.GetString("Show_Subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Subtitles on Mouse Hover 的本地化字符串。
        /// </summary>
        public static string Show_Subtitles_on_Mouse_Hover {
            get {
                return ResourceManager.GetString("Show_Subtitles_on_Mouse_Hover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Small 的本地化字符串。
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snapshot 的本地化字符串。
        /// </summary>
        public static string Snapshot {
            get {
                return ResourceManager.GetString("Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snapshot Folder 的本地化字符串。
        /// </summary>
        public static string Snapshot_Folder {
            get {
                return ResourceManager.GetString("Snapshot_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snapshot Shortcut 的本地化字符串。
        /// </summary>
        public static string Snapshot_Shortcut {
            get {
                return ResourceManager.GetString("Snapshot_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software Language 的本地化字符串。
        /// </summary>
        public static string Software_Language {
            get {
                return ResourceManager.GetString("Software_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subtitle Font Size 的本地化字符串。
        /// </summary>
        public static string Subtitle_Font_Size {
            get {
                return ResourceManager.GetString("Subtitle_Font_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subtitle Opacity 的本地化字符串。
        /// </summary>
        public static string Subtitle_Opacity {
            get {
                return ResourceManager.GetString("Subtitle_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subtitle Style 的本地化字符串。
        /// </summary>
        public static string Subtitle_Style {
            get {
                return ResourceManager.GetString("Subtitle_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subtitles 的本地化字符串。
        /// </summary>
        public static string Subtitles {
            get {
                return ResourceManager.GetString("Subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video 的本地化字符串。
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vocabulary 的本地化字符串。
        /// </summary>
        public static string Vocabulary_Book {
            get {
                return ResourceManager.GetString("Vocabulary_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume Shortcut 的本地化字符串。
        /// </summary>
        public static string Volume_Shortcut {
            get {
                return ResourceManager.GetString("Volume_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Word Click 的本地化字符串。
        /// </summary>
        public static string Word_Click {
            get {
                return ResourceManager.GetString("Word_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Language 的本地化字符串。
        /// </summary>
        public static string Your_Language {
            get {
                return ResourceManager.GetString("Your_Language", resourceCulture);
            }
        }
    }
}
